internal_api_base_url: ""
guild_id: "979445890064470036"
wom_api_base_url: "https://api.wiseoldman.net/v2"

default_csv_path: "./data/signups.csv"
output_csv_path: "./data/draft_ratings.csv"
cache_directory: "./data_cache"

wom_event_ids:
  - 

custom_ehb_weights:
  "tzhaar_ket_raks_challenges": 0.0
  "inferno": 1.0
  "fortis_colosseum": 1.0
  "theatre_of_blood_hard_mode": 0.3
  "theatre_of_blood": 0.15
  "chambers_of_xeric_challenge_mode": 0.2
  "chambers_of_xeric": 0.1
  "tombs_of_amascut_expert": 0.2

ca_tier_values:
  Grandmaster: 40
  Master: 25
  Elite: 10
  Hard: 5

event_percentile_weights:
  top_10_percent: 40
  top_25_percent: 25
  above_median: 10
